apiVersion: v1
kind: ConfigMap
metadata:
  name: releases-info
  namespace: default
data:
  versions: |
    docker.io/bitnami/postgresql:14.5.0-debian-11-r35
    docker.io/cr.fluentbit.io/fluent/fluent-bit:1.9.8
    docker.io/kindest/kindnetd:v20230511-dc714da8
    docker.io/kindest/local-path-provisioner:v20230511-dc714da8
    docker.io/nicolaka/netshoot:latest
    ghcr.io/fluxcd/helm-controller:v0.36.2
    ghcr.io/fluxcd/kustomize-controller:v1.1.1
    ghcr.io/fluxcd/notification-controller:v1.1.0
    ghcr.io/fluxcd/source-controller:v1.1.2
    ghcr.io/weaveworks/wego-app:v0.38.0
    registry.k8s.io/coredns/coredns:v1.10.1
    registry.k8s.io/etcd:3.5.7-0
    registry.k8s.io/kube-apiserver:v1.27.3
    registry.k8s.io/kube-controller-manager:v1.27.3
    registry.k8s.io/kube-proxy:v1.27.3
    registry.k8s.io/kube-scheduler:v1.27.3