apiVersion: v1
kind: ServiceAccount
metadata:
  name: releases-info-scraper-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: releases-info-scraper-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["list", "create", "get", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: releases-info-scraper-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: releases-info-scraper-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: releases-info-scraper-clusterrole
  apiGroup: rbac.authorization.k8s.io
