registry.k8s.io/etcd:3.5.7-0
registry.k8s.io/coredns/coredns:v1.10.1
registry.k8s.io/kube-proxy:v1.27.3
registry.k8s.io/kube-controller-manager:v1.27.3
docker.io/kindest/kindnetd:v20230511-dc714da8
docker.io/kindest/local-path-provisioner:v20230511-dc714da8
docker.io/backstage:1.0.0
registry.k8s.io/kube-scheduler:v1.27.3
registry.k8s.io/kube-apiserver:v1.27.3
docker.io/postgres:13.2-alpine
