# registry.k8s.io/kube-scheduler:v1.27.3
# registry [registry.k8s.io] UNSUPPORTED now

# docker.io/nginx/nginx-ingress:3.1.1
nginx-ingress:
  dockerhub:
    owner: nginx
    repo: nginx-ingress
  version: 3.1.1

# registry.k8s.io/etcd:3.5.7-0
# registry [registry.k8s.io] UNSUPPORTED now

# registry.k8s.io/kube-controller-manager:v1.27.3
# registry [registry.k8s.io] UNSUPPORTED now

# docker.io/library/scraper-test:0.1.2
scraper-test:
  dockerhub:
    owner: library
    repo: scraper-test
  version: 0.1.2

# registry.k8s.io/coredns/coredns:v1.10.1
# registry [registry.k8s.io] UNSUPPORTED now

# docker.io/kindest/local-path-provisioner:v20230511-dc714da8
local-path-provisioner:
  dockerhub:
    owner: kindest
    repo: local-path-provisioner
  version: v20230511-dc714da8

# registry.k8s.io/kube-proxy:v1.27.3
# registry [registry.k8s.io] UNSUPPORTED now

# docker.io/nicolaka/netshoot:latest
netshoot:
  dockerhub:
    owner: nicolaka
    repo: netshoot
  version: latest

# docker.io/kindest/kindnetd:v20230511-dc714da8
kindnetd:
  dockerhub:
    owner: kindest
    repo: kindnetd
  version: v20230511-dc714da8

# registry.k8s.io/kube-apiserver:v1.27.3
# registry [registry.k8s.io] UNSUPPORTED now

# docker.io/nginx:latest
nginx:
  dockerhub:
    owner: library
    repo: nginx
  version: latest

